name: Build and deploy Python app to Azure Web App - EcoDynlab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Django
        run: |
          pip install django

      - name: Set up Conda
        shell: bash
        run: |
          conda env create -f environment.yml
          conda info --envs
          conda activate SERVIR_AppTemplate
          
      #- uses: conda-incubator/setup-miniconda@v2
        #with:
          #activate-environment: SERVIR_AppTemplate
          #environment-file: environment.yml
          #auto-activate-base: false
      #- run: |
          #conda info
          #conda list
      #- run: conda install -c anaconda django
      #- run: python -c "import sys; print(sys.path)"
      - name: Install GDAL
        run: |
          brew update
          brew install gdal
      #sudo apt-get install -y python3-dev


          
      
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'EcoDynlab'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C50C95E03C764C49A3D6FB4D9C81B053 }}
